# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b94d3f32571ada20e8db881d2a866796652e30aba6da71dbae9d14fed902dbe43ca7bd308b33a08987c5a8a9dbf2707da3011119c0b349ee6fc4bb48bc748c

test:
  secret_key_base: 9b2d5d289ca367559d15bc0b5c2cd5e7bd1843b85fcb978f6fc4f322d609c00a327be927907496537cc1cf685b743d2182ce4e86cff92ed523208ee970b3772b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
